export const STOCKS = {
  IONQ:["아이온큐","양자"],SNDK:["샌디스크","반도체"],AVGO:["브로드컴","반도체"],ORCL:["오라클","AI 인프라"],QLD:["나스닥 2배","ETF"],
  NVDA:["엔비디아","반도체"],AMD:["AMD","반도체"],TSM:["TSMC","반도체"],ASML:["ASML","반도체"],MU:["마이크론","반도체"],ARM:["Arm","반도체"],
  PLTR:["팔란티어","AI 소프트웨어"],CRWV:["코어위브","AI 인프라"],VRT:["버티브","AI 인프라"],IREN:["IREN","AI 인프라"],NBIS:["네비우스","AI 인프라"],
  RKLB:["로켓랩","우주"],ASTS:["AST 스페이스모바일","우주"],QBTS:["D-Wave","양자"],RGTI:["리게티","양자"],OKLO:["오클로","원전"],SMR:["NuScale","원전"],LEU:["센트러스","원전"],
  COIN:["코인베이스","디지털자산"],MSTR:["스트래티지","디지털자산"],HOOD:["로빈후드","핀테크"],TSLA:["테슬라","모빌리티"],
  SPY:["S&P 500","ETF"],QQQ:["나스닥 100","ETF"],SMH:["반도체 ETF","ETF"],SOXX:["반도체 ETF","ETF"],IWM:["러셀 2000","ETF"],GLD:["금 ETF","ETF"],TLT:["미 장기채","ETF"],XLE:["에너지 ETF","ETF"],XLF:["금융 ETF","ETF"],
};
export const MACROS = [["^GSPC","S&P 500","index"],["^NDX","나스닥 100","index"],["^SOX","필라델피아 반도체","index"],["^RUT","러셀 2000","index"],["^VIX","VIX","index"],["DX-Y.NYB","DXY","index"],["KRW=X","USD/KRW","index"],["CL=F","WTI","usd"]];
const finite=v=>v!==null&&v!==undefined&&(typeof v!=="string"||v.trim()!=="")&&Number.isFinite(Number(v));
const round=(v,d=2)=>finite(v)?Number(Number(v).toFixed(d)):null;
const average=v=>v.length?v.reduce((s,x)=>s+x,0)/v.length:null;
const sma=(v,p)=>v.length>=p?average(v.slice(-p)):average(v);
const SESSION_LABELS={PREMARKET:"프리마켓",REGULAR:"정규장",AFTER_HOURS:"시간외"};
function attachSeries(row,series){Object.defineProperty(row,"_series",{value:series,enumerable:false,configurable:true});return row}
function latestFinitePoint(result){const c=result?.indicators?.quote?.[0]?.close||[],t=result?.timestamp||[];for(let i=Math.min(c.length,t.length)-1;i>=0;i--)if(finite(c[i])&&finite(t[i]))return{price:Number(c[i]),timestamp:Number(t[i])};return null}
function periodSession(meta,timestamp){const p=meta.currentTradingPeriod||{};for(const [k,s] of [["pre","PREMARKET"],["regular","REGULAR"],["post","AFTER_HOURS"]])if(finite(p[k]?.start)&&finite(p[k]?.end)&&timestamp>=Number(p[k].start)&&timestamp<=Number(p[k].end))return s;return null}
export function selectYahooSessionQuote(result={}){const m=result.meta||{},state=String(m.marketState||"CLOSED").toUpperCase(),explicit={PREMARKET:finite(m.preMarketPrice)?{price:Number(m.preMarketPrice),timestamp:Number(m.preMarketTime||0)}:null,REGULAR:finite(m.regularMarketPrice)?{price:Number(m.regularMarketPrice),timestamp:Number(m.regularMarketTime||0)}:null,AFTER_HOURS:finite(m.postMarketPrice)?{price:Number(m.postMarketPrice),timestamp:Number(m.postMarketTime||0)}:null},latest=latestFinitePoint(result),ss=state.startsWith("PRE")?"PREMARKET":state.startsWith("POST")?"AFTER_HOURS":state==="REGULAR"?"REGULAR":null,ls=latest?(ss||periodSession(m,latest.timestamp)||(finite(m.regularMarketTime)&&latest.timestamp>Number(m.regularMarketTime)?"AFTER_HOURS":"REGULAR")):null;let selected=null;if(ss){selected=[explicit[ss],latest&&ls===ss?latest:null].filter(Boolean).sort((a,b)=>(b.timestamp||0)-(a.timestamp||0))[0]||explicit.REGULAR||latest}else{const c=Object.entries(explicit).filter(([,q])=>q).map(([session,q])=>({...q,session}));if(latest)c.push({...latest,session:ls||"REGULAR"});selected=c.sort((a,b)=>(b.timestamp||0)-(a.timestamp||0))[0]||null}if(!selected||!finite(selected.price))return null;const ps=selected.session||(selected===explicit.PREMARKET?"PREMARKET":selected===explicit.AFTER_HOURS?"AFTER_HOURS":ss||ls||"REGULAR");return{price:Number(selected.price),timestamp:Number(selected.timestamp||m.regularMarketTime||0),priceSession:ps,sessionLabel:SESSION_LABELS[ps]||"정규장",marketState:state}}
export function rsi(values,period=14){if(values.length<period+1)return null;const c=values.slice(1).map((v,i)=>v-values[i]).slice(-period),g=c.map(x=>Math.max(0,x)),l=c.map(x=>Math.max(0,-x)),ag=average(g),al=average(l);if(!al)return 100;return 100-100/(1+ag/al)}
function volatility(values,period=20){const s=values.slice(-(period+1));if(s.length<3)return null;const r=s.slice(1).map((v,i)=>Math.log(v/s[i])).filter(finite),m=average(r),variance=average(r.map(x=>(x-m)**2));return Math.sqrt(variance)*Math.sqrt(252)*100}
export function calculateSignal({price,previousClose,closes,highs,lows,volumes}){
  const ma5=sma(closes,5),ma20=sma(closes,20),ma60=sma(closes,60),ma120=sma(closes,120);
  const momentum=rsi(closes),vol=volatility(closes),rv=volumes.filter(finite).slice(-21),cv=rv.at(-1),bv=average(rv.slice(0,-1)),vr=finite(cv)&&finite(bv)&&bv>0?cv/bv:null;
  const g20=finite(ma20)?(price/ma20-1)*100:null,g60=finite(ma60)?(price/ma60-1)*100:null,cp=finite(previousClose)&&previousClose!==0?(price/previousClose-1)*100:null;
  const lowSeries=lows.filter(finite),highSeries=highs.filter(finite);
  const support=Math.min(...lowSeries.slice(-20)),resistance=Math.max(...highSeries.slice(-20));
  const prior20High=highSeries.length>1?Math.max(...highSeries.slice(-21,-1)):null;
  const prior10Low=lowSeries.length>1?Math.min(...lowSeries.slice(-11,-1)):null;
  const maStack=finite(ma5)&&finite(ma20)&&finite(ma60)&&finite(ma120)
    ? (price>ma5&&ma5>ma20&&ma20>ma60&&ma60>ma120?"정배열":price<ma5&&ma5<ma20&&ma20<ma60&&ma60<ma120?"역배열":"혼조")
    : "확인 중";
  const turtleSignal=finite(prior20High)&&price>prior20High?"20일 돌파":finite(prior10Low)&&price<prior10Low?"10일 이탈":maStack==="정배열"?"추세유지":"대기";
  let score=50;
  if(finite(g20))score+=g20>0?12:-12;
  if(finite(g60))score+=g60>0?10:-10;
  if(finite(ma20)&&finite(ma60))score+=ma20>ma60?8:-8;
  if(maStack==="정배열")score+=6; else if(maStack==="역배열")score-=6;
  if(turtleSignal==="20일 돌파")score+=8; else if(turtleSignal==="10일 이탈")score-=8;
  if(finite(momentum))score+=momentum>=50&&momentum<=68?8:momentum>78?-14:momentum<32?-6:0;
  if(finite(vr))score+=vr>=1.5?8:vr>=1.1?4:0;
  if(finite(cp))score+=cp>0?4:-4;
  if(finite(vol)&&vol>90)score-=8;
  score=Math.max(0,Math.min(100,Math.round(score)));
  const signal=momentum>78||score<=34||turtleSignal==="10일 이탈"?"주의":score>=70?"주목":score>=58?"관찰":"대기";
  const reasons=[];
  if(finite(g20))reasons.push(`20일선 대비 ${g20>=0?"상단":"하단"} ${Math.abs(g20).toFixed(1)}%`);
  if(maStack!=="확인 중")reasons.push(`MA 5/20/60/120 ${maStack}`);
  if(turtleSignal!=="대기")reasons.push(`터틀 ${turtleSignal}`);
  if(finite(momentum))reasons.push(`RSI ${momentum.toFixed(0)}`);
  if(finite(vr))reasons.push(`20일 평균 대비 거래량 ${vr.toFixed(2)}배`);
  return{changePct:round(cp),score,signal,rsi:round(momentum,1),ma5:round(ma5),ma20:round(ma20),ma60:round(ma60),ma120:round(ma120),ma20Gap:round(g20),ma60Gap:round(g60),maStack,turtleSignal,turtle20High:round(prior20High),turtle10Low:round(prior10Low),volumeRatio:round(vr),volatility20:round(vol,1),support:finite(support)?round(support):null,resistance:finite(resistance)?round(resistance):null,trend:finite(ma20)&&finite(ma60)?(price>ma20&&ma20>ma60?"상승":price<ma20&&ma20<ma60?"하락":"혼조"):"확인 중",reasons}
}
async function yahooChart(symbol,range="6mo",interval="1d"){const url=`https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(symbol)}?range=${range}&interval=${interval}&includePrePost=true&events=div%2Csplits`,response=await fetch(url,{headers:{"user-agent":"Mozilla/5.0 StrategyBar/1.0","accept":"application/json"}});if(!response.ok)throw new Error(`Yahoo ${symbol} HTTP ${response.status}`);const p=await response.json(),r=p?.chart?.result?.[0];if(!r)throw new Error(`Yahoo ${symbol} empty`);return r}
function quoteFromResult(symbol,result,name,category){const q=result.indicators?.quote?.[0]||{},m=result.meta||{},closes=(q.close||[]).filter(finite).map(Number),highs=(q.high||[]).filter(finite).map(Number),lows=(q.low||[]).filter(finite).map(Number),volumes=(q.volume||[]).filter(finite).map(Number),selected=selectYahooSessionQuote(result),price=selected?.price??(finite(m.regularMarketPrice)?Number(m.regularMarketPrice):closes.at(-1)),previousClose=finite(m.chartPreviousClose)?Number(m.chartPreviousClose):finite(m.previousClose)?Number(m.previousClose):closes.at(-2);if(!finite(price))throw new Error(`${symbol} price missing`);const signal=calculateSignal({price,previousClose,closes,highs,lows,volumes});return attachSeries({symbol,name,category,price:round(price),previousClose:round(previousClose),...signal,open:finite(m.regularMarketOpen)?round(m.regularMarketOpen):null,dayHigh:finite(m.regularMarketDayHigh)?round(m.regularMarketDayHigh):null,dayLow:finite(m.regularMarketDayLow)?round(m.regularMarketDayLow):null,volume:finite(m.regularMarketVolume)?Number(m.regularMarketVolume):volumes.at(-1)||null,marketState:selected?.marketState||m.marketState||null,priceSession:selected?.priceSession||"REGULAR",sessionLabel:selected?.sessionLabel||"정규장",asOf:selected?.timestamp?new Date(selected.timestamp*1000).toISOString():new Date().toISOString(),source:"Yahoo Finance",provider:"Yahoo",providerPriority:3},closes)}
function macroFromResult(key,result,name,unit){const q=result.indicators?.quote?.[0]||{},m=result.meta||{},selected=selectYahooSessionQuote(result),closes=(q.close||[]).filter(finite).map(Number),value=selected?.price??(finite(m.regularMarketPrice)?Number(m.regularMarketPrice):closes.at(-1)),prev=finite(m.chartPreviousClose)?Number(m.chartPreviousClose):finite(m.previousClose)?Number(m.previousClose):closes.at(-2);return{key,name,unit,value:round(value),previousClose:round(prev),changePct:finite(value)&&finite(prev)&&prev!==0?round((value/prev-1)*100):null,changeValue:finite(value)&&finite(prev)?round(value-prev):null,asOf:selected?.timestamp?new Date(selected.timestamp*1000).toISOString():new Date().toISOString(),source:"Yahoo Finance",provider:"Yahoo",providerPriority:3,priceSession:selected?.priceSession||"REGULAR",sessionLabel:selected?.sessionLabel||"정규장"}}
export function applyExternalSessionQuote(row={},quote={}){if(!finite(quote.price))return row;const price=Number(quote.price),previousClose=finite(quote.previousClose)?Number(quote.previousClose):row.previousClose,changePct=finite(previousClose)&&previousClose!==0?(price/previousClose-1)*100:row.changePct;return{...row,price:round(price),previousClose:round(previousClose),changePct:round(changePct),priceSession:quote.priceSession||row.priceSession,sessionLabel:quote.sessionLabel||SESSION_LABELS[quote.priceSession]||row.sessionLabel,asOf:quote.asOf||row.asOf,source:quote.source||row.source,provider:quote.provider||row.provider,providerPriority:quote.providerPriority??row.providerPriority}}
async function resilientVix(){for(const host of ['query1.finance.yahoo.com','query2.finance.yahoo.com']){try{const url=`https://${host}/v8/finance/chart/%5EVIX?range=5d&interval=5m&includePrePost=true`,r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 StrategyBar/1.0','accept':'application/json'}});if(!r.ok)continue;const p=await r.json(),result=p?.chart?.result?.[0];if(!result)continue;const row=macroFromResult('^VIX',result,'VIX','index');if(finite(row.value)&&row.value>5&&row.value<100)return{...row,source:'Yahoo Finance VIX',provider:'Yahoo',providerPriority:2}}catch{}}throw new Error('VIX providers unavailable')}
export async function fetchMarketSnapshot(stockEntries=Object.entries(STOCKS),extraSymbol=null){const stockPairs=[...stockEntries];if(extraSymbol&&!STOCKS[extraSymbol])stockPairs.push([extraSymbol,[extraSymbol,"사용자 추가"]]);const stockResults=await Promise.all(stockPairs.map(async([symbol,[name,category]])=>{try{return[symbol,quoteFromResult(symbol,await yahooChart(symbol),name,category),null]}catch(error){return[symbol,null,error instanceof Error?error.message:String(error)]}}));const macroResults=await Promise.all(MACROS.map(async([key,name,unit])=>{try{return[macroFromResult(key,await yahooChart(key,"5d","5m"),name,unit),null]}catch(error){return[null,`${name}: ${error instanceof Error?error.message:String(error)}`]}}));const symbols=Object.fromEntries(stockResults.filter(([,row])=>row).map(([symbol,row])=>[symbol,row]));const market=macroResults.filter(([row])=>row).map(([row])=>row);let vix=market.find(x=>x.key==='^VIX'&&finite(x.value));if(!vix){try{vix=await resilientVix();const i=market.findIndex(x=>x.key==='^VIX');if(i>=0)market[i]=vix;else market.push(vix)}catch(error){market.push({key:'^VIX',name:'VIX',value:null,source:'Yahoo Finance VIX',provider:'Yahoo',error:error instanceof Error?error.message:String(error)})}}const errors=[...stockResults.filter(([,row,error])=>!row&&error).map(([symbol,,error])=>({symbol,error})),...macroResults.filter(([,error])=>error).map(([,error])=>({symbol:"macro",error}))];return{ok:Object.keys(symbols).length>0,asOf:new Date().toISOString(),session:symbols.SPY?.priceSession||"REGULAR",symbols,market,errors,sources:[...new Set([...Object.values(symbols).map(r=>r.source),...market.map(r=>r.source)].filter(Boolean))]}}
